//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Deura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> NumberContact { get; set; }
        public Nullable<int> Budgets { get; set; }
        public bool isActive { get; set; }
        public string CampaignCode { get; set; }
        public string Domain { get; set; }
    }
}
