//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Deura
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignOption
    {
        public int Id { get; set; }
        public Nullable<int> Local_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Campaign_Id { get; set; }
        public Nullable<int> Script_id { get; set; }
        public Nullable<System.DateTime> CreatAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string Code { get; set; }
    }
}
