//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Deura
{
    using System;
    using System.Collections.Generic;
    
    public partial class pg_data_import
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string center { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string Sent_log { get; set; }
        public string CampaignCode { get; set; }
    }
}
