//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Deura
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string EmailSignature { get; set; }
        public string agent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public string source { get; set; }
        public Nullable<int> LoaiTK { get; set; }
        public Nullable<int> idParent { get; set; }
        public Nullable<int> idCity { get; set; }
        public Nullable<int> idManager { get; set; }
        public Nullable<int> idWork { get; set; }
        public int idGroup { get; set; }
        public Nullable<int> idCenter { get; set; }
        public string TeamName { get; set; }
    }
}
