//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Deura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MobilePREntities : DbContext
    {
        public MobilePREntities()
            : base("name=MobilePREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<center> center { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Source> Source { get; set; }
        public virtual DbSet<Working> Working { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ScritpStore> ScritpStore { get; set; }
        public virtual DbSet<CampaignOption> CampaignOption { get; set; }
        public virtual DbSet<CampaignType> CampaignType { get; set; }
        public virtual DbSet<CampaignStore> CampaignStore { get; set; }
        public virtual DbSet<pg_data> pg_data { get; set; }
        public virtual DbSet<Domain> Domain { get; set; }
        public virtual DbSet<Campaign> Campaign { get; set; }
        public virtual DbSet<pg_data_import> pg_data_import { get; set; }
        public virtual DbSet<SMS_logs> SMS_logs { get; set; }
        public virtual DbSet<Group> Group { get; set; }
    
        public virtual ObjectResult<Data_Manager_PageList_Result> Data_Manager_PageList(string search, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Data_Manager_PageList_Result>("Data_Manager_PageList", searchParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<Data_Manager_PageList_By_TeamLead_Result> Data_Manager_PageList_By_TeamLead(Nullable<int> id_teamlead, string search, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var id_teamleadParameter = id_teamlead.HasValue ?
                new ObjectParameter("id_teamlead", id_teamlead) :
                new ObjectParameter("id_teamlead", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Data_Manager_PageList_By_TeamLead_Result>("Data_Manager_PageList_By_TeamLead", id_teamleadParameter, searchParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<Data_Manager_PageList_By_TeamLead2_Result> Data_Manager_PageList_By_TeamLead2(Nullable<int> id_teamlead, string search, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var id_teamleadParameter = id_teamlead.HasValue ?
                new ObjectParameter("id_teamlead", id_teamlead) :
                new ObjectParameter("id_teamlead", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Data_Manager_PageList_By_TeamLead2_Result>("Data_Manager_PageList_By_TeamLead2", id_teamleadParameter, searchParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<Data_Manager_PageList_By_City_Result> Data_Manager_PageList_By_City(Nullable<int> idCity, string search, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var idCityParameter = idCity.HasValue ?
                new ObjectParameter("idCity", idCity) :
                new ObjectParameter("idCity", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Data_Manager_PageList_By_City_Result>("Data_Manager_PageList_By_City", idCityParameter, searchParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    }
}
