//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Deura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working
    {
        public int Id { get; set; }
        public string WorkName { get; set; }
        public string Descriptions { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
